/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

/**
 * @class
 * Initializes a new instance of the Gateway class.
 * @constructor
 * A Power BI Gateway
 * @member {string} [id] The gateway id
 * 
 * @member {string} [name] The gateway name
 * 
 * @member {string} [type] The gateway type
 * 
 * @member {object} [publicKey] The gateway name
 * 
 * @member {string} [publicKey.exponent] The public key exponent
 * 
 * @member {string} [publicKey.modulud] The public key  modulus
 * 
 */
function Gateway() {
}

/**
 * Defines the metadata of Gateway
 *
 * @returns {object} metadata of Gateway
 *
 */
Gateway.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Gateway',
    type: {
      name: 'Composite',
      className: 'Gateway',
      modelProperties: {
        id: {
          required: false,
          serializedName: 'id',
          type: {
            name: 'String'
          }
        },
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        type: {
          required: false,
          serializedName: 'type',
          type: {
            name: 'String'
          }
        },
        publicKey: {
          required: false,
          serializedName: 'publicKey',
          type: {
            name: 'Composite',
            className: 'GatewayPublicKey'
          }
        }
      }
    }
  };
};

module.exports = Gateway;
