/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the ImportModel class.
 * @constructor
 * The import object
 * @member {string} [id] The import id
 * 
 * @member {string} [name] The import name name
 * 
 * @member {string} [importState] The import upload state
 * 
 * @member {array} [reports] The reports associated with this import
 * 
 * @member {array} [datasets] The datasets associated with this import
 * 
 */
function ImportModel() {
}

/**
 * Defines the metadata of ImportModel
 *
 * @returns {object} metadata of ImportModel
 *
 */
ImportModel.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Import',
    type: {
      name: 'Composite',
      className: 'ImportModel',
      modelProperties: {
        id: {
          required: false,
          serializedName: 'id',
          type: {
            name: 'String'
          }
        },
        name: {
          required: false,
          serializedName: 'name',
          type: {
            name: 'String'
          }
        },
        importState: {
          required: false,
          serializedName: 'importState',
          type: {
            name: 'String'
          }
        },
        reports: {
          required: false,
          serializedName: 'reports',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'ReportElementType',
                type: {
                  name: 'Composite',
                  className: 'Report'
                }
            }
          }
        },
        datasets: {
          required: false,
          serializedName: 'datasets',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'DatasetElementType',
                type: {
                  name: 'Composite',
                  className: 'Dataset'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = ImportModel;
