/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ImportInfo class.
 * @constructor
 * The import info
 * @member {string} [filePath] The file path to import
 * 
 * @member {string} [connectionType] The import connection type
 * 
 */
function ImportInfo() {
}

/**
 * Defines the metadata of ImportInfo
 *
 * @returns {object} metadata of ImportInfo
 *
 */
ImportInfo.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ImportInfo',
    type: {
      name: 'Composite',
      className: 'ImportInfo',
      modelProperties: {
        filePath: {
          required: false,
          serializedName: 'filePath',
          type: {
            name: 'String'
          }
        },
        connectionType: {
          required: false,
          serializedName: 'connectionType',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = ImportInfo;
