/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the ODataResponsestring class.
 * @constructor
 * Odata response wrapper for a string
 * @member {string} [odatacontext]
 * 
 * @member {string} [value] The returned value
 * 
 */
function ODataResponsestring() {
}

/**
 * Defines the metadata of ODataResponsestring
 *
 * @returns {object} metadata of ODataResponsestring
 *
 */
ODataResponsestring.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'ODataResponse[string]',
    type: {
      name: 'Composite',
      className: 'ODataResponsestring',
      modelProperties: {
        odatacontext: {
          required: false,
          serializedName: 'odata\\.context',
          type: {
            name: 'String'
          }
        },
        value: {
          required: false,
          serializedName: 'value',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = ODataResponsestring;
