/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

var models = require('./index');

var util = require('util');

/**
 * @class
 * Initializes a new instance of the Table class.
 * @constructor
 * A dataset table
 * @member {string} name The table name
 * 
 * @member {array} columns The column schema for this table
 * 
 * @member {array} [rows] The data rows within this tabe
 * 
 */
function Table() {
}

/**
 * Defines the metadata of Table
 *
 * @returns {object} metadata of Table
 *
 */
Table.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Table',
    type: {
      name: 'Composite',
      className: 'Table',
      modelProperties: {
        name: {
          required: true,
          serializedName: 'name',
          constraints: {
            Pattern: '^[\x09\x0A\x0D\x20\x23\x2D\x30-\x39\x40-\x5A\x5E-\x5F\x61-\x7A\x7E-\uD7FF\uE000-\uFFFD\u10000-\u10FFFF]{1,100}$'
          },
          type: {
            name: 'String'
          }
        },
        columns: {
          required: true,
          serializedName: 'columns',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'ColumnElementType',
                type: {
                  name: 'Composite',
                  className: 'Column'
                }
            }
          }
        },
        rows: {
          required: false,
          serializedName: 'rows',
          type: {
            name: 'Sequence',
            element: {
                required: false,
                serializedName: 'RowElementType',
                type: {
                  name: 'Composite',
                  className: 'Row'
                }
            }
          }
        }
      }
    }
  };
};

module.exports = Table;
