/*
 * Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

'use strict';

/**
 * @class
 * Initializes a new instance of the Workspace class.
 * @constructor
 * A Power BI Workspace
 * @member {string} [workspaceId] The workspace id
 * 
 * @member {string} [workspaceCollectionName] The workspace collection name
 * 
 */
function Workspace() {
}

/**
 * Defines the metadata of Workspace
 *
 * @returns {object} metadata of Workspace
 *
 */
Workspace.prototype.mapper = function () {
  return {
    required: false,
    serializedName: 'Workspace',
    type: {
      name: 'Composite',
      className: 'Workspace',
      modelProperties: {
        workspaceId: {
          required: false,
          serializedName: 'workspaceId',
          type: {
            name: 'String'
          }
        },
        workspaceCollectionName: {
          required: false,
          serializedName: 'workspaceCollectionName',
          type: {
            name: 'String'
          }
        }
      }
    }
  };
};

module.exports = Workspace;
